### PR TITLE
Add SineReLU to the activation list

### PR DESCRIPTION
**Pull request by djthegr8**
See [here](https://medium.com/@wilder.rodrigues/sinerelu-an-alternative-to-the-relu-activation-function-e46a6199997d) for the reference.

### CODE REVIEW

**Comment by CarloLucibello** [comment]
we don't add a new activation just because someone made medium article about it

**Comment by djthegr8** [comment]
It isn't plainly a medium article. Anyways, it is included in the
keras.contrib functions...

**Comment by ToucheSir** [comment]
Though I don't believe there's a formal threshold for what should and shouldn't belong in NNlib, I think it's fair to expect the following from any new activation function:
1. Some kind of publication (a pre-print is fine) with background motivation and reasonably comprehensive testing.
2. Enough name recognition + common usage in publications, libraries or frameworks beyond the original author's work.

In this case, SineReLU was added to keras-contrib via a PR by _the same author_ of the medium article. It also does not appear in any other libraries or model implementations with a sizeable following (i.e. GitHub stars). I couldn't find a formal paper describing it either, so unless the author forgot to link one in their medium post the grounds for this are even shakier.

Lastly, I'm not sure what keras-contrib's grounds for contributions are, but it seems like they're very much a "kitchen sink" model where all functionality is _caveat emptor_ and may not ever make it upstream. On those terms, Flux/NNlib are probably closer to TF/Keras proper, PyTorch or JAX in that we require a somewhat higher burden of proof before adding new features.

**Comment by djthegr8** [comment]
Cool, thanks!

**Pull request closed without merging**
