### PR TITLE
WIP: Support for asymmetrical padding

### PR DESCRIPTION
**Pull request by ianshmean**
Based on discussion at https://github.com/FluxML/Flux.jl/issues/258

### CODE REVIEW

**Comment by staticfloat** [comment]
I just wanted to quickly note here that although my recently-merged `im2col()` rewrite has clobbered the diff here, I kept this PR in mind so adapting to the new `im2col()` should be very easy.  Let me know if you have any questions!

**Comment by MikeInnes** [comment]
(And apologies for not getting to this earlier -- but it'd be great to get it in!)

**Comment by staticfloat** [comment]
@ianshmean Thanks for your effort here; I incorporated these changes into my recent overhaul of NNlib, and with https://github.com/FluxML/Flux.jl/pull/718, we have full asymmetric padding support!

**Comment by ianshmean** [comment]
@staticfloat Great! That makes building out YOLO a lot easier (save the loss functions, which I've not found the time to finish)

**Pull request closed without merging**
