### PR TITLE
Bump deps

### PR DESCRIPTION
**Pull request by pxl-th**
- Use `1.10` in Buildkite CI (and `nightly` for CUDA).
- Use `lts`, `1` and `pre` in GitHub CI.
- Add compat GPUArraysCore for `0.2`.
- Bump ChainRulesCore to `0.25`.
- [x] Need to wait for AMDGPU@1.1 release: https://github.com/JuliaGPU/AMDGPU.jl/commit/4385ed941d5bf1b4818d8cd34ca090b8827d1ca4

### PR Checklist

- [ ] Tests are added
- [ ] Documentation, if applicable

### CODE REVIEW

**Review by CarloLucibello — APPROVED** [review]

**Comment by CarloLucibello** [comment]
What's going on with all these failing tests?

**Comment by pxl-th** [comment]
Don't know for sure yet, but my guess is this is due to GPUArrays@11 which moved  to KernelAbstractions for kernel backed.
I'll take a look in a bit

**Comment by pxl-th** [comment]
Needs `JLArrays` and `ChainRules` to include `GPUArraysCore@0.2` compat bump in their releases to fix the errors. So let's wait for those.

**Comment by pxl-th** [comment]
Waiting on https://github.com/JuliaArrays/StructArrays.jl/pull/317 as it blocks an update (direct dependency of ChainRules.jl)

**Comment by pxl-th** [comment]
The error with CUDA in buildkite CI is likely due to it initially installing GPUArrays@11, but then when reaching CUDA tests, it downgrades to GPUArrays@10 (because release of CUDA.jl does not yet include 11) and then this happens:
```
┌ Warning: Module GPUCompiler with build ID fafbfcfd-0ba2-0013-0007-a0064bea54e3 is missing from the cache.
│ This may mean GPUCompiler [61eb1bfa-7361-4325-ad38-22787b887f55] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1948
┌ Warning: Module GPUArraysCore with build ID fafbfcfd-8fc1-a5dc-0007-a0067d2e04d5 is missing from the cache.
│ This may mean GPUArraysCore [46192b85-c4d5-4398-a991-12ede77f4527] does not support precompilation but is imported by a module that does.
└ @ Base loading.jl:1948
```
and it actually uses GPUArrays@11 thus all the errors

**Comment by pxl-th** [comment]
Should be good to go. All issues are fixed.

**Pull request merged**
