### PR TITLE
export batched_mul!

### PR DESCRIPTION
**Pull request by bjarthur**
fixes https://github.com/FluxML/NNlib.jl/issues/333

### CODE REVIEW

**Comment by bjarthur** [comment]
@mcabbott

**Comment by DhairyaLGandhi** [comment]
Thank you, I've started ci on it. Do we also care about a `batched_vec`? We can and probably should reuse the batched ops directly.

**Comment by ToucheSir** [comment]
`batched_vec` is already exported, I think the question in #333 was whether there should be an in-place implementation of that as well.

**Comment by DhairyaLGandhi** [comment]
Ah, of course. Just checked that it's exported.

**Pull request merged**
