### PR TITLE
Use a thread-sharded `col` in `im2col`-related functions

### PR DESCRIPTION
**Pull request by staticfloat**
Fixes https://github.com/FluxML/NNlib.jl/issues/158

### CODE REVIEW

**Comment by oxinabox** [comment]
my code in #158 now errors with
```
julia> r4 = conv(x, w, cdims)

ERROR: MethodError: no method matching #conv_im2col!#159(::Array{Float64,3}, ::Float64, ::Float64, ::typeof(NNlib.conv_im2col!), ::Array{Fl
oat64,5}, ::Array{Float64,5}, ::Array{Float64,5}, ::DenseConvDims{3,(3, 1, 1),3,3,(1, 1, 1),(0, 0, 0, 0, 0, 0),(1, 1, 1),false})
Closest candidates are:
  #conv_im2col!#159(::AbstractArray{T,2}, ::T, ::T, ::typeof(NNlib.conv_im2col!), ::AbstractArray{T,5}, ::AbstractArray{T,5}, ::AbstractArr
ay{T,5}, ::DenseConvDims) where T at /Users/oxinabox/JuliaEnvs/NNlib.jl/src/impl/conv_im2col.jl:30
Stacktrace:
 [1] conv_im2col!(::Array{Float64,5}, ::Array{Float64,5}, ::Array{Float64,5}, ::DenseConvDims{3,(3, 1, 1),3,3,(1, 1, 1),(0, 0, 0, 0, 0, 0),
(1, 1, 1),false}) at /Users/oxinabox/JuliaEnvs/NNlib.jl/src/impl/conv_im2col.jl:30
 [2] #conv!#41(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(conv!), ::Array{Float64,5}, ::Array{Float64
,5}, ::Array{Float64,5}, ::DenseConvDims{3,(3, 1, 1),3,3,(1, 1, 1),(0, 0, 0, 0, 0, 0),(1, 1, 1),false}) at /Users/oxinabox/JuliaEnvs/NNlib.
jl/src/conv.jl:53
 [3] conv!(::Array{Float64,5}, ::Array{Float64,5}, ::Array{Float64,5}, ::DenseConvDims{3,(3, 1, 1),3,3,(1, 1, 1),(0, 0, 0, 0, 0, 0),(1, 1,
1),false}) at /Users/oxinabox/JuliaEnvs/NNlib.jl/src/conv.jl:53
 [4] #conv!#47(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::typeof(conv!), ::Array{Float64,3}, ::Array{Float64
,3}, ::Array{Float64,3}, ::DenseConvDims{1,(3,),3,3,(1,),(0, 0),(1,),false}) at /Users/oxinabox/JuliaEnvs/NNlib.jl/src/conv.jl:70
 [5] #conv#89 at /Users/oxinabox/JuliaEnvs/NNlib.jl/src/conv.jl:70 [inlined]
 [6] conv(::Array{Float64,3}, ::Array{Float64,3}, ::DenseConvDims{1,(3,),3,3,(1,),(0, 0),(1,),false}) at /Users/oxinabox/JuliaEnvs/NNlib.jl
/src/conv.jl:114
 [7] top-level scope at REPL[15]:1
```

**Comment by oxinabox** [comment]
My tests now pass

**Comment by staticfloat** [comment]
Awesome, thanks Lyndon.  @andreasnoack can you verify that this PR solves your observed issues as well?

**Comment by andreasnoack** [comment]
I can confirm that the example in https://github.com/FluxML/Flux.jl/issues/982 produces correct result with this branch of NNlib.

**Pull request merged**
