### PR TITLE
scatter cleanup and fix min/max

### LINKED ISSUE #317: add rrules for max/min scatter
Couldn't see this through in  #297 since there was a bug

### PR DESCRIPTION
**Pull request by CarloLucibello**
Fix #317. The main problem was in the use of FiniteDifferences' central difference method on singularities of non-smooth functions.

### CODE REVIEW

**Comment by yuehhua** [comment]
I am quite curious about the semantic difference between `DoesNotExist` and `NoTangent`.

**Comment by CarloLucibello** [comment]
> I am quite curious about the semantic difference between `DoesNotExist` and `NoTangent`.

no difference, just a recent renaming in ChainRulesCore.jl

**Comment by yuehhua** [comment]
Maybe we could come out with a new name for `_check_dims`? Maybe `_check_scatter_dims` or something else?

**Comment by yuehhua** [comment]
For `scatter`, I have been used to write something like this.

```julia
scatter(op,
        src::AbstractArray{Tsrc,Nsrc},
        idx::AbstractArray{Tidx,Nidx};
        init = scatter_empty(op, Tsrc))
```
I think it can avoid the branching on `isnothing` or not.

**Comment by yuehhua** [comment]
The dimension checking is slightly different for `scatter` and `gather`. `scatter` calls `_check_dims`/`scatter_dims` with `(dst, src, idx)`, while, reversely, `gather` calls `_check_dims`/`scatter_dims` with `(src, dst, idx)`. For abstraction, I give `_check_dims`/`scatter_dims` a signature of `(X, Y, idx)`, so they are both available for `scatter` and `gather`.

**Comment by yuehhua** [comment]
I am good with this PR.

**Comment by CarloLucibello** [comment]
buildkite fail is unrelated, merging

**Pull request merged**
