### PR TITLE
Adding ForwardDiff fix for sigmoid.

### PR DESCRIPTION
**Pull request by sambitdash**
This is a sample PR for changes needed for ForwardDiff.Duals. The derivatives can be computed as simple operations on orginal functions than resorting to situations where `Inf`/`Inf` or `Inf`*0  can arise leading to potential NaNs.

### CODE REVIEW

**Comment by sambitdash** [comment]
A detailed approrach may be worked out for all activation methods as discussed in #164 or #78.

**Comment by MikeInnes** [comment]
Can you elaborate on the changes to ForwardDiff.Dual and why it needs this rewrite? Why can't we continue using `σ_stable`?

**Comment by sambitdash** [comment]
@MikeInnes, 

My proposed solution is not just for sigmoid but any such function where such situation can arise, although it has been found in sigmoid to start with we can look at other potential situations on a case to case basis. 

In Julia if you were to define 1/(1+exp(-x)) it's stable. Julia's infinte maths takes care of cases like `1/Inf` cases and accurately maps to `0`. 

While it's possible in the computation of the ForwardDiff method the generic differentiation computation is not able to address such corner cases and leading to `Inf/Inf` or `0/0` cases which is mapping the data to `NaN`.

The earlier implementation clipped the negative value arbitrarily to -80 which as documented was considered as a hack (as per the comment in the code). The primary intent of such a code would have been valid had Julia not been able to handle `Inf` maths properly. That's not the case here. 

Here the issue is `ForwardDiff` code is not handling the numerical computation of derivatives in an `Inf` aware manner. And the proposed solution was spcific to addressing that issue. Since, derivative of sigmoid can be written as polynomial of sigmoid this can be very easily addressed by rewriting the `Dual`. Similarly, for `tanh` and other functions as well.

**Comment by MikeInnes** [comment]
Ok, I thought you meant there had been recent forwarddiff changes that this was in response to.

Having a cutoff is not completely arbitrary since the point where `NaN`s arise is exactly the point where the result of `σ` is indistinguishable from zero. But analytically simplifying the gradient to avoid that issue entirely obviously seems better than defining cutoffs for all floating point types. So I agree this seems like a good way to go. We shouldn't need it for most functions since things like `tanh` are defined analytically by ForwardDiff already.

**Comment by sambitdash** [comment]
If you are in agreement with these changes, I will add a few test cases as may be needed for this PR and submit specifically for `sigmoid` only.

**Comment by cossio** [comment]
Please see https://github.com/FluxML/NNlib.jl/pull/198 for a simpler fix.

**Comment by CarloLucibello** [comment]
this PR is not needed anymore, thanks in any case

**Pull request closed without merging**
