### PR TITLE
test multithreaded

### PR DESCRIPTION
**Pull request by oxinabox**
Since i ran into #158 
I figure good to test multhreaded.

TravisCI only gives us 2 cores so thats what we can do.

This gives us at least  a chance that CI will catch something going wrong this way.

### CODE REVIEW

**Comment by dhairyagandhi96** [comment]
Can we continue to test on older Julia versions? Otherwise lgtm

**Comment by oxinabox** [comment]
1.1 isn't LTS, nor current stable.
We could keep it, but why 1.1 and not 1.2?

---

Hmm seems like the env isn't getting caught into the matrix of Travis tests...

**Comment by dhairyagandhi96** [comment]
Ideally would like to include 1.2 in the testing suite, as a sanity check

Maybe try to break it down with GROUP in Travis?

**Comment by CarloLucibello** [comment]
I think testing on the lowest supported julia version and the last one is fine. Also, we are also doubling the computational load of CI here. I'll have CI run again before merging

**Comment by CarloLucibello** [comment]
ops, this should have been merged time ago. Rebase?

**Comment by CarloLucibello** [comment]
this has been done in a recent PR

**Pull request closed without merging**
