### PR TITLE
allow type of x and w to differ in conv

### PR DESCRIPTION
**Pull request by jbrea**
Trying to address #39

### CODE REVIEW

**Comment by MikeInnes** [comment]
Thanks! Given that the type parameters are now not used in most cases, these can be written as `A::AbstractArray, B::AbstractArray`; hope you don't mind making that quick change.

**Comment by jbrea** [comment]
I simplified some instances, as you suggested. Do you prefer to do this replacement everywhere?
`maxpool!(y::A, x::A, k; kw...) where A<:AbstractArray` looks nicely succinct.

**Comment by JobJob** [comment]
IMO makes sense to make the same change everywhere relevant in conv.jl. Restricting args to be the exact same type sounds like it was just a historical accident, and `similar` for many AbstractArray types returns a different type (often a straight up Array) - which is relevant e.g. here: https://github.com/FluxML/NNlib.jl/blob/085adb7ca8ad57a11515d0396b6b120ab929216f/src/conv.jl#L155-L157

**Comment by MikeInnes** [comment]
Agreed. I'll merge this once tests pass, and I'm happy to take more patches to clean this up.

**Pull request merged**
