### PR TITLE
act: implement exponential linear unit

### PR DESCRIPTION
**Pull request by iblis17**

### CODE REVIEW

**Comment by MikeInnes** [comment]
This is great, thanks. Small tweak – could you change the `1` literals to `one(x)`? (The `0` in the comparison is fine as is, I think).

**Comment by iblis17** [comment]
done 👌

**Comment by iblis17** [comment]
🤔 , no idea why GH do not update yet

**Comment by MikeInnes** [comment]
Github was just having a slow day yesterday. Thanks for the patch!

**Pull request merged**
