### PR TITLE
Fixes #555

### LINKED ISSUE #555: Broken rrule for pad_constant()
The following code throws me an error:

```
using NNlib, ChainRulesCore
x = ones(2, 3)
pad_constant(x, (1, 0), 0.0; dims=1)  # works fine
_, back = rrule(pad_constant, x, (1, 0), 0.0; dims=1)
back(ones(3, 3))
```
```
ERROR: MethodError: no method matching gen_pad(::Tuple{Int64, Int64}, ::Int64, ::Int64)

Closest candidates are:
  gen_pad(::Tuple{Vararg{Int64, L}}, ::Tuple{Vararg{Int64, D}}, ::Any) where {L, D}
   @ NNlib C:\Users\koenv\.julia\packages\NNlib\EtyxF\src\padding.jl:115
  gen_pad(::Any, ::Colon, ::Any)
   @ NNlib C:\Users\koenv\.julia\packages\NNlib\EtyxF\src\padding.jl:113
  gen_pad(::Int64, ::Int64, ::Any)
   @ NNlib C:\Users\koenv\.julia\packages\NNlib\EtyxF\src\padding.jl:114
  ...

Stacktrace:
 [1] (::NNlib.var"#pad_constant_pullback#512"{2, Int64, Matrix{Float64}, Tuple{Int64, Int64}})(Δ::Float64)
   @ NNlib C:\Users\koenv\.julia\packages\NNlib\EtyxF\src\padding.jl:153
 [2] top-level scope
   @ c:\Users\koenv\.julia\packages\NNlib\sXmAj\src\NNlib_pad_constant_error.jl:5
```
Version info:
```
Julia Version 1.9.4
Commit 8e5136fa29 (2023-11-14 08:46 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: 32 × 13th Gen Intel(R) Core(TM) i9-13900K
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, goldmont)
  Threads: 24 on 32 virtual cores
Environment:
  JULIA_EDITOR = code
  JULIA_NUM_THREADS = 24

  [872c559c] NNlib v0.9.9
  [d360d2e6] ChainRulesCore v1.19.0
```

### PR DESCRIPTION
**Pull request by re1san**
It fixes the issue #555 where we need to convert Int type dimension to a Tuple

### CODE REVIEW

**Review by ToucheSir — COMMENTED** [review]
Thanks! Could you add a short test for this so we can catch if it breaks in the future?

**Comment by re1san** [comment]
sure, can you please guide me where to add it (sry if its a noob question, I am new)

from what I am guessing I have to add it in [this file](https://github.com/FluxML/NNlib.jl/blob/master/test/padding.jl)

**Comment by ToucheSir** [comment]
Yes, I think copying and modifying one of the tests from https://github.com/FluxML/NNlib.jl/blob/3b1ff90d5f61c66125adc8698f038f38d4329c4e/test/padding.jl#L11-L18 should be enough.

**Comment by re1san** [comment]
Added tests

**Review by ToucheSir — APPROVED** [review]
Thanks!

**Pull request merged**
