### PR TITLE
Use KernelAbstractions.jl for gather/scatter kernels

### PR DESCRIPTION
**Pull request by pxl-th**
Depends on #486.
Successfully tested on `CPU`, `CUDABackend`, `ROCBackend`.

Since LLVM does not support certain atomic operations (fmin, fmax, fmul, fdiv) tests for them are disabled when using such backends, which is currently only `ROCBackend`:
https://llvm.org/docs/LangRef.html#atomicrmw-instruction

fmin/fmax requires LLVM 15+: https://reviews.llvm.org/D127041

### TODO

- [x] Add `@inbounds`.

### PR Checklist

- [x] Tests are added
- [ ] Documentation, if applicable

### CODE REVIEW

**Comment by pxl-th** [comment]
It may be that LLVM on Julia 1.6 is too old and we cann't support all of the ops that we currently support for CUDA.
On 1.9-rc2 it fails for `-` op.

As an alternative, we can retain (for now) NNlibCUDA scatter.

**Comment by ToucheSir** [comment]
FWIW the copy of NNlibCUDA in this repo doesn't do anything at present, so we need to make sure the overloads in the standalone NNlibCUDA repo still work.

**Comment by pxl-th** [comment]
> FWIW the copy of NNlibCUDA in this repo doesn't do anything at present, so we need to make sure the overloads in the standalone NNlibCUDA repo still work.

IIC, if NNlibCUDA in this repo is not registered, then tests at [`using NNlibCUDA`](https://github.com/pxl-th/NNlib.jl/blob/99f6ed4098df95e21fcea0a4797780daf1d32fb9/test/runtests.jl#L96) line should import the standalone repo.
And I've [disabled](https://github.com/pxl-th/NNlib.jl/blob/99f6ed4098df95e21fcea0a4797780daf1d32fb9/test/runtests.jl#L57) `Gather` and `Scatter` tests from test suite for CUDA, because we [call](https://github.com/pxl-th/NNlib.jl/blob/99f6ed4098df95e21fcea0a4797780daf1d32fb9/test/runtests.jl#L98) them from NNlibCUDA tests.

**Comment by pxl-th** [comment]
Not sure what's with CUDA on 1.8...
Will investigate in a bit

**Comment by pxl-th** [comment]
Probably was some kind of hiccup, now the CI passes.

**Review by ToucheSir — APPROVED** [review]
Anything left before merging?

**Comment by pxl-th** [comment]
> Anything left before merging?

I think no, should be good to go

**Pull request merged**
