### PR TITLE
Add hand written gelu derivative

### PR DESCRIPTION
**Pull request by chengchingwen**

### CODE REVIEW

**Review by CarloLucibello — APPROVED** [review]

**Comment by CarloLucibello** [comment]
you have some timings for it?

**Comment by chengchingwen** [comment]
>  you have some timings for it?

before:
```
julia> CUDA.@time CUDA.@sync Flux.gradient((m, x)->sum(sin.(m(x))), gpu(Dense(512, 512, gelu)), gpu(randn(512, 128, 16)));
  0.058803 seconds (37.33 k CPU allocations: 16.095 MiB) (17 GPU allocations: 54.004 MiB, 0.69% memmgmt time)

julia> @btime CUDA.@sync Flux.gradient((m, x)->sum(sin.(m(x))), $(gpu(Dense(512, 512, gelu))), $(gpu(randn(512, 128, 16))));
  387.026 μs (523 allocations: 27.28 KiB)
```

after:
```
julia> CUDA.@time CUDA.@sync Flux.gradient((m, x)->sum(sin.(m(x))), gpu(Dense(512, 512, gelu)), gpu(randn(512, 128, 16)));
  0.062451 seconds (37.29 k CPU allocations: 16.076 MiB) (16 GPU allocations: 46.004 MiB, 0.61% memmgmt time)

julia> @btime CUDA.@sync Flux.gradient((m, x)->sum(sin.(m(x))), $(gpu(Dense(512, 512, gelu))), $(gpu(randn(512, 128, 16))));
  356.649 μs (482 allocations: 25.56 KiB)
```

**Comment by chengchingwen** [comment]
@mcabbott Do you want to check the numerical accuracy? Or it is good to go?

**Comment by mcabbott** [comment]
Looks good, I don't think any of the gradients have been carefully checked to measure floating point accuracy.

Saves 2 copies by avoiding Zygote's broadcasting with `Dual`.

**Pull request merged**
