### PR TITLE
Fix output shape of ∇conv_data_direct!

### LINKED ISSUE #156: ∇conv_data_direct produces incorrectly shaped output for 5D arrays
The channel and batch dimensions are swapped; for example:

```
using Flux: ConvTranspose
using NNlib: ∇conv_data_im2col, ∇conv_data_direct

ct = ConvTranspose((2, 2, 2), 4=>5, stride=2)
mat = Float32.(rand(16, 16, 16, 4, 3));
∇conv_data_im2col(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
# (32, 32, 32, 5, 3)
∇conv_data_direct(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
# (32, 32, 32, 3, 5)
```

### PR DESCRIPTION
**Pull request by matsueushi**
Fixes #156, https://github.com/FluxML/Flux.jl/issues/978

```julia
julia> using Flux

julia> using Flux: ConvTranspose, conv_transpose_dims

julia> using NNlib: ∇conv_data_im2col, ∇conv_data_direct

julia> ct = ConvTranspose((2, 2, 2), 4=>5, stride=2)
ConvTranspose((2, 2, 2), 4=>5)

julia> mat = Float32.(rand(16, 16, 16, 4, 3));

julia> ∇conv_data_im2col(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
(32, 32, 32, 5, 3)

julia> ∇conv_data_direct(mat, ct.weight, conv_transpose_dims(ct, mat)) |> size
(32, 32, 32, 5, 3)
```

### CODE REVIEW

**Comment by staticfloat** [comment]
Can you add a test case so that we can make sure to never break this again?  It's hard to remember sometimes where `transpose_swapbatch()` should be used and where it shouldn't.  ;)

**Comment by matsueushi** [comment]
Sure. Will do.

**Comment by matsueushi** [comment]
Is it enough to check the size of outputs from direct convs with that of original inputs?

**Comment by staticfloat** [comment]
Yep, looks perfect!

**Pull request merged**
