### PR TITLE
introduce trilinear upsampling

### PR DESCRIPTION
**Pull request by maxfreu**
Hi everybody!

This introduces trilinear (3D) upsampling on GPU. Maybe we can rethink the dispatch; I think the code can be deflated by smart choices.

### CODE REVIEW

**Comment by maxfreu** [comment]
Ööhm it should be, isn‘t it? :)

**Comment by CarloLucibello** [comment]
Seems like you are based on an old commit, NNlibCUDA now is here https://github.com/FluxML/NNlibCUDA.jl

**Comment by maxfreu** [comment]
Oh I see. Why did you move it out? Now I have to make 2 forks, 2 branches, 2 PRs and the possibility of version incompatibilities arises.

**Comment by CarloLucibello** [comment]
yeah, I agree, I wanted to keep it here in fact but didn't get much support https://github.com/FluxML/NNlib.jl/issues/300

**Comment by maxfreu** [comment]
Just updated this PR. NNlibCUDA will follow.

**Comment by maxfreu** [comment]
For completeness I just added the CPU implementation as well. Lots of duplicate code, but works.

**Comment by CarloLucibello** [comment]
this looks ready, should we merge it @maxfreu ?

**Comment by maxfreu** [comment]
You can if you want to :) https://github.com/FluxML/NNlibCUDA.jl/pull/5 is also ready. Or should I squash everything into one commit first?

**Pull request merged**
