### PR TITLE
Add generic fallbacks for rrules not expecting Thunks

### PR DESCRIPTION
**Pull request by DhairyaLGandhi**
And bump ChainRules* to 1.x

supersedes #338 

cc @oxinabox

### CODE REVIEW

**Comment by DhairyaLGandhi** [comment]
Also cc @ChrisRackauckas

**Comment by oxinabox** [comment]
You probably want to cherry pick this commit:
https://github.com/FluxML/NNlib.jl/pull/338/commits/f9d78aa64b72feaefd3b50b4b0460025a56818bd

**Comment by DhairyaLGandhi** [comment]
Thank you, yes I was doing the same thing, let me cherry pick instead.

**Review by oxinabox — APPROVED** [review]

**Comment by DhairyaLGandhi** [comment]
https://buildkite.com/julialang/flux-dot-jl/builds/1496#7bb3aa82-4fcd-4b7f-a3c9-e3de7006c4fa fails Flux tests due to ComponentArrays.

**Pull request merged**
